import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FaSearch, FaPhone, FaVideo, FaEllipsisV } from "react-icons/fa";
import Navigator from "../content/Navigator";
import GroupContent from "../content/GroupContent";
import FriendContent from "../content/FriendContent";
import Messages from "../content/Messages";
import Sender from "../content/Sender";
export default function Dashboard({ socket }) {
    console.log(socket);
    return (_jsxs("div", { className: "bg-slate-700 h-screen p-5 flex space-x-6 overflow-hidden", children: [_jsx("div", { className: "w-fit sm:w-fit xl:w-64 bg-blue-600 p-4 sm:p-8  rounded md:rounded-2xl overflow-y-auto ", children: _jsx(Navigator, {}) }), _jsxs("div", { className: "w-1/3 bg-transparent rounded-2xl flex flex-col space-y-12", children: [_jsxs("div", { className: "flex bg-black w-full h-fit rounded-xl md:p-1 lg:p-2 xl:p-3 space-x-6", children: [_jsx("div", { className: "w-8 h-8", children: _jsx(FaSearch, { className: "text-white", size: '100%' }) }), _jsx("input", { type: 'search', placeholder: "Search", className: "bg-transparent w-full placeholder:text-gray-600 outline-0 text-white" })] }), _jsxs("div", { className: "grid grid-rows-2 w-full space-y-10 overflow-y-auto h-full", children: [_jsx("div", { className: "bg-black rounded-2xl ", children: _jsx(GroupContent, {}) }), _jsx("div", { className: "bg-black rounded-2xl ", children: _jsx(FriendContent, {}) })] })] }), _jsxs("div", { className: "w-1/2  bg-black py-4 px-6 rounded-2xl flex flex-col", children: [_jsxs("div", { className: "flex justify-between border-b border-slate-700 pb-6", children: [_jsxs("div", { className: "flex space-x-4 items-center", children: [_jsx("div", { children: _jsx("img", { src: "/b.jpg", alt: "", className: "w-16 h-16 object-cover rounded-full bg-transparent " }) }), _jsxs("div", { className: "flex flex-col", children: [_jsx("div", { className: "text-white font-semibold text-xl", children: "Swahili" }), _jsx("div", { className: "text-gray-400", children: "Online" })] })] }), _jsxs("div", { className: "flex space-x-8 items-center", children: [_jsx(FaPhone, { className: "rotate-90 text-blue-500 w-6 h-6" }), _jsx(FaVideo, { className: "text-blue-500 w-6 h-6" }), _jsx(FaEllipsisV, { className: "text-blue-500 w-6 h-6" })] })] }), _jsxs("div", { className: "h-full flex flex-col space-y-4 ", children: [_jsx("div", { className: "h-4/6", children: _jsx(Messages, {}) }), _jsx("div", { className: "h-1/6 flex items-center", children: _jsx(Sender, {}) })] }), _jsx("div", {})] })] }));
}
